#
# Azure Pipeline for Source driven deployments using Salesforce DX
#
#
# Run these commands before executing any build jobs,
# such as to install dependencies and set environment variables
#
name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  var1: value1
jobs:
- job: One
  steps:
  - script: echo First step!